In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',
     'I am batman']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'I am batman']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good',
 'I am batman']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
#the number corresponds to the 1 value for a word at that index and remaining all are zeros in the vocab size
#for example the word 'glass' has index value "9869" which represents out of 10000 vocab at 9869 index we get 1 as value and remaining all are zeros.

[[4394, 9869, 4273, 7385],
 [4394, 9869, 4273, 3941],
 [4394, 500, 4273, 6519],
 [2898, 2367, 2005, 3536, 2624],
 [2898, 2367, 2005, 3536, 2580],
 [9334, 4394, 4941, 4273, 7373],
 [6483, 3473, 5906, 3536],
 [2898, 2367, 5497]]

In [7]:
#Word embedding representataion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [8]:
#We need to make every sentence of fixed length, this can be done using pad sequences
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4394 9869 4273 7385]
 [   0    0    0    0 4394 9869 4273 3941]
 [   0    0    0    0 4394  500 4273 6519]
 [   0    0    0 2898 2367 2005 3536 2624]
 [   0    0    0 2898 2367 2005 3536 2580]
 [   0    0    0 9334 4394 4941 4273 7373]
 [   0    0    0    0 6483 3473 5906 3536]
 [   0    0    0    0    0 2898 2367 5497]]


In [9]:
## feature representation
dim=10

In [15]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_shape=(sent_length,)))
model.compile('adam','mse')

c:\Users\kumma\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 348ms/step


array([[[ 2.13394277e-02,  3.44163068e-02,  3.07531394e-02,
          1.46103986e-02, -4.07436602e-02, -1.04070418e-02,
         -3.54346037e-02, -4.07014042e-03, -3.35169211e-02,
         -3.14409621e-02],
        [ 2.13394277e-02,  3.44163068e-02,  3.07531394e-02,
          1.46103986e-02, -4.07436602e-02, -1.04070418e-02,
         -3.54346037e-02, -4.07014042e-03, -3.35169211e-02,
         -3.14409621e-02],
        [ 2.13394277e-02,  3.44163068e-02,  3.07531394e-02,
          1.46103986e-02, -4.07436602e-02, -1.04070418e-02,
         -3.54346037e-02, -4.07014042e-03, -3.35169211e-02,
         -3.14409621e-02],
        [ 2.13394277e-02,  3.44163068e-02,  3.07531394e-02,
          1.46103986e-02, -4.07436602e-02, -1.04070418e-02,
         -3.54346037e-02, -4.07014042e-03, -3.35169211e-02,
         -3.14409621e-02],
        [ 2.26232521e-02,  1.45350806e-02,  3.13526057e-02,
         -7.67334551e-03,  3.76535393e-02,  1.48142613e-02,
          1.69299953e-02,  2.72556432e-02, -1.681182

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531